config:
  bdtopo_path: bdtopo/ADRESSE.shp
  census_path: rp_2015/FD_INDCVIZE_2015.dbf
  data_path: /data/assets/lyon
  departments:
  - '01'
  - 38
  - 42
  - 69
  - 69M
  gtfs_path: gtfs/GTFS_TCL.ZIP;gtfs/export_gtfs_voyages.zip;gtfs/export-intercites-gtfs-last.zip;gtfs/export-ter-gtfs-last.zip;gtfs/CAPI.GTFS.zip;gtfs/GTFS_RX.ZIP;gtfs/SEM-GTFS.zip;gtfs/stas.gtfs.zip;gtfs/VIENNE.GTFS.zip
  hts: entd
  java_memory: 40G
  lead_path: /srv/app/lead
  lead_year: 2022
  memory: 40g
  osm_path: osm/rhone-alpes-latest.osm.pbf
  output_path: /srv/app/output
  output_prefix: lead_
  processes: 12
  random_seed: 1234
  regions: []
  sampling_rate: 1.0
run:
- synthesis.output
working_directory: /data/assets/lyon/cache
